config/routes.rb
RubyOnRailsActiverecord::Application.routes.draw do

  resources :mensajes

  root 'home#index'

  get 'join' => 'curso_activerecord#index'
  get 'join/joinSQL' => 'curso_activerecord#joins_sql'
  get 'join/join' => 'curso_activerecord#joins'
  get 'join/scope' => 'curso_activerecord#scope'
  
  get 'serializar' => 'serializar_objeto#index'
  get 'serializar/meta' => 'serializar_objeto#serializado_meta'
  get 'serializar/basic' => 'serializar_objeto#serializado'
  get 'serializar/custom' => 'serializar_objeto#serializado_custom'

  get 'email' => 'enviar_email#index'
  get 'email/send' => 'enviar_email#enviar'

  get 'validation' => 'curso_validaciones#index'
  post 'validation/create' => 'curso_validaciones#create'

  get 'mensaje/json' => 'mensajes#json'
  get 'mensaje/xml' => 'mensajes#xml'

  

end

app/models/direccion.rb
class Direccion < ActiveRecord::Base
	belongs_to :usuario
    has_many :telefonos
end

app/models/factura.rb
class Factura < ActiveRecord::Base
    belongs_to :usuario
end

app/models/mensaje.rb
class Mensaje
#incluimos los módulos que vamos a utilizar   
  include ActiveModel::Validations  #necesario para agregar las condiciones de validacion
  include ActiveModel::Conversion # contiene entre otras cosas el metodo to_key que usamos en el formulario
  include ActiveModel::Serializers::JSON
  include ActiveModel::Serializers::Xml

  
#declaramos las variables del modelo    
  attr_accessor :nombre, :email, :contenido

#Agregamos las condicones a vailidar    
  validates_presence_of :nombre, :email, :contenido
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates_format_of :email, { :with => VALID_EMAIL_REGEX , message: "El formato del correo es invalido" }
  validates_length_of :contenido, :maximum => 500

# El constructor que recibe un hash con los valores del formulario
#  y nos crea nuestro objeto mensaje  
  def initialize(attributes = {})
    attributes.each do |nombre, value|
      send("#{nombre}=", value)
    end
  end
  
  # Metodo que debemos agregar a nuestro modelo
  # ya que no se van a guardar los datos en la base de datos
  def persisted?
    false
  end

  def attributes
    {'nombre' => nil,"email" =>nil, "contenido"=>nil}
  end

end

app/models/persona.rb
class Persona < ActiveRecord::Base

	# Confirmamos el email y validamos que no sean vacios con presence
	# mostramos el mensaje de error con message
  	validates :email , presence: true , confirmation: true 
  	validates :email_confirmation, presence: { message: " es requerido"}

  	# Validamos en una expresion regular nuestro email
  	 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, format: { :with => VALID_EMAIL_REGEX , message: "El formato del correo es invalido" }

	# Validamos que el identificador tenga entre o a 12 caracteres
	validates :identificador, length: { in: 8..12 , message: "debe tener entre 8 y 12 caracteres"}

	# Validamos que el identificador solo sea numerico
	validates :identificador, numericality: { only_integer: true }

	# Validamos que el email sea unico
	validates :email, uniqueness: {case_sensitive: false ,message: "ya esta registrado"}
end

app/models/telefono.rb
class Telefono < ActiveRecord::Base
    belongs_to :direccion
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base

  scope :masculino, -> { where(sexo: "m") }
  scope :mayor_que, ->(time) { where("nacimiento < ?", time) }

	has_many :direccions
	has_many :facturas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/curso_activerecord_controller.rb
class CursoActiverecordController < ApplicationController

  def index
	@usuarios    = Usuario.all
	@direccions  = Direccion.all
	@facturas    = Factura.all
	@telefonos   = Telefono.all
  end

  def joins_sql
	@usuarios    = Usuario.joins('INNER JOIN direccions ON direccions.usuario_id = usuarios.id')
  end


  def joins
	@ejemplo1    = Usuario.joins(:direccions)
	@ejemplo2    = Usuario.joins(:direccions, :facturas)
	@ejemplo3    = Usuario.joins( direccions: :telefonos)
	@ejemplo4    = Usuario.joins(:direccions).where(direccions: {pais: 'Venezuela'})
  end

  def scope
	@ejemplo1    = Usuario.masculino
	@ejemplo2    = Usuario.mayor_que(Time.zone.parse("1988-05-09"))
	@ejemplo3    = Usuario.masculino.mayor_que(Time.zone.parse("1988-05-09"))
  end

end

app/controllers/curso_validaciones_controller.rb
class CursoValidacionesController < ApplicationController

  def index
  	# Crea una persona nueva para cargarla con informacion
  	@nuevo_usuario = Persona.new
  	 # Carga todas las personas de base de datos
	@usuarios    = Persona.all
  end
  
  def create
  
  # Recibe y crea una persona con los datos del formulario
    @nuevo_usuario = Persona.new(params[:nuevo_usuario].permit(:nombre, :email,:identificador, :telefono,:sexo,:email_confirmation))
	@usuarios    = Persona.all

	# intenta guardar en base de datos
      if @nuevo_usuario.save
      	#si tiene exito nos lleva al index
		redirect_to validation_path
      else
      	# si no carga nuevamente la vista con los errores a corregir
         render action: 'index' 
      end
  end

end

app/controllers/enviar_email_controller.rb
class EnviarEmailController < ApplicationController

	def index		

  	end

  	def enviar		
		@persona1 = Persona.create({ nombre: 'Ricardo Sampayo', email: 'me@ricardosampayo.com',email_confirmation: 'me@ricardosampayo.com', identificador: "123456789", sexo: 'm', telefono: '123456789123' })
		ActionCorreo.bienvenido_email(@persona1).deliver
        render json: @persona1
  	end
  	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

   	def index

  	end

end

app/controllers/mensajes_controller.rb
class MensajesController < ApplicationController

  def index
    @mensaje = Mensaje.new
  end

  def json
  @mensaje = Mensaje.new({'nombre' => 'Ricardo Sampayo',
                          "email" =>'me@RicardoSampayo.com', 
                          "contenido"=>'Este es un mensaje para CodeHero'})
  render :json => @mensaje.to_json
  end

  def xml
    @mensaje = Mensaje.new({'nombre' => 'Ricardo Sampayo',
                            "email" =>'me@RicardoSampayo.com', 
                            "contenido"=>'Este es un mensaje para CodeHero'})
    render :xml => @mensaje.to_xml
  end
  
  def create
  
    @mensaje = Mensaje.new(params[:mensaje])


    if @mensaje.valid?

      flash[:notice] = "Se envio el mensaje con exito"
      redirect_to mensajes_path
   
    else
      
      render :action => 'index'
    
    end
  end


end

app/controllers/serializar_objeto_controller.rb
class SerializarObjetoController < ApplicationController

  	def index

	end

	def serializado
		@ejemplo1    = Usuario.all
		render json: @ejemplo1 
  	end

  	def serializado_meta
		@ejemplo1    = Usuario.all
		render json: @ejemplo1  , meta: {autor: 'www.codeHero.co'}, meta_key: 'meta_object'
  	end

  	def serializado_custom
		@ejemplo1    = Usuario.all
		render json: @ejemplo1 , each_serializer: UsuarioCustomSerializer
  	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/curso_activerecord_helper.rb
module CursoActiverecordHelper
end

app/helpers/curso_validaciones_helper.rb
module CursoValidacionesHelper
end

app/helpers/enviar_email_helper.rb
module EnviarEmailHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mensajes_helper.rb
module MensajesHelper
end

app/helpers/serializar_objeto_helper.rb
module SerializarObjetoHelper
end

app/views/action_correo/bienvenido_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Bienvenido a CodeHero.co, <%= @user.nombre %></h1>
    <p>
      Tu correo ha sido enviado satisfactoriamente y su identificador es:
      <%= @user.identificador %>.<br/>
    </p>
    <p>
      Recuerda visitarnos en: <a href="<%= @url %>">CodeHero.co</a>
    </p>
    <p>Te recomiendo echarle un vistazo a la serie completa de Ruby on Rails desde cero, así como a las otras series de CodeHero, agradeciendo de antemano todas sus dudas y comentarios en la sección de comentarios.</p>
    <p>¡Hasta el próximo capítulo!</p>
  </body>
</html>

app/views/curso_activerecord/index.html.erb
<h1>Ejemplos del tutorial <a href="http://codehero.co/activerecord-parte-2/">Ruby on Rails desde Cero: ActiveRecord parte 2</a></h1>
<br>  
<ul>
  <li><h3><%= link_to 'Joins con fragmentos de SQL', join_joinSQL_path %></h3></li>
  <li><h3><%= link_to 'Joins con herramientas Rails', join_join_path %></h3></li>
  <li><h3><%= link_to 'Scope', join_scope_path %></h3></li>
</ul>
<br>  


<h2>Datos de las tablas que estaremos utilizando</h2>
<h3>Usuarios</h3>

<table class ="table table-bordered">
  <thead>
    <tr>
      <th>id</th>
      <th>nombre</th>
      <th>apellido</th>
      <th>nacimiento</th>
      <th>sexo</th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.id %></td>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.nacimiento %></td>
        <td><%= usuario.sexo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>   

<h3>Direcciones</h3>

<table class ="table table-bordered">
  <thead>
    <tr>
      <th>id</th>
      <th>calle</th>
      <th>zona</th>
      <th>país</th>
      <th>ciudad</th>
      <th>usuario</th>
    </tr>
  </thead>

  <tbody>
    <% @direccions.each do |direccion| %>
      <tr>
        <td><%= direccion.id %></td>
        <td><%= direccion.calle %></td>
        <td><%= direccion.zona %></td>
        <td><%= direccion.pais %></td>
        <td><%= direccion.ciudad %></td>
        <td><%= direccion.usuario.id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>   

<h3>Teléfonos</h3>

<table class ="table table-bordered">
  <thead>
    <tr>
      <th>id</th>
      <th>teléfono</th>
      <th>tipo</th>
      <th>dirección</th>
    </tr>
  </thead>

  <tbody>
    <% @telefonos.each do |telefono| %>
      <tr>
        <td><%= telefono.id %></td>
        <td><%= telefono.telefono %></td>
        <td><%= telefono.tipo %></td>
        <td><%= telefono.direccion.id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>   

<h3>Facturas</h3>

<table class ="table table-bordered">
  <thead>
    <tr>
      <th>id</th>
      <th>referencia</th>
      <th>monto</th>
      <th>usuario</th>
    </tr>
  </thead>

  <tbody>
    <% @facturas.each do |factura| %>
      <tr>
        <td><%= factura.id %></td>
        <td><%= factura.referencia %></td>
        <td><%= factura.monto %></td>
        <td><%= factura.usuario.id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>   

app/views/curso_activerecord/joins.html.erb
<h1>Ejemplo1: joins básico</h1>
<p>Todos los usuarios que tienen una al menos una direccion</p>
<p><b>RAILS:</b>      Usuario.joins(:direccions)</p>
<p><b>SQL:</b>        SELECT usuarios.* FROM usuarios INNER JOIN direccions ON direccions.usuario_id = usuarios.id</p>
<table class ="table table-bordered">
  <thead>
    <tr>
      <th>id</th>
      <th>nombre</th>
      <th>apellido</th>
      <th>nacimiento</th>
      <th>sexo</th>
    </tr>
  </thead>

  <tbody>
    <% @ejemplo1.each do |usuario| %>
      <tr>
        <td><%= usuario.id %></td>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.nacimiento %></td>
        <td><%= usuario.sexo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>   


<h1>Ejemplo1: joins compuesto</h1>
<p>todos los usuarios con al menos una dirección y una factura</p>
<p><b>RAILS:</b>      Usuario.joins(:direccions, :facturas)</p>
<p><b>SQL:</b>        SELECT usuarios.* FROM usuarios
  INNER JOIN direccions ON usuarios.usuario_id= direccions.id
  INNER JOIN facturas ON facturas.usuario_id = usuarios.id</p>
<table class ="table table-bordered">
  <thead>
    <tr>
      <th>id</th>
      <th>nombre</th>
      <th>apellido</th>
      <th>nacimiento</th>
      <th>sexo</th>
    </tr>
  </thead>

  <tbody>
    <% @ejemplo2.each do |usuario| %>
      <tr>
        <td><%= usuario.id %></td>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.nacimiento %></td>
        <td><%= usuario.sexo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>  

<h1>Ejemplo3: joins asociaciones anidadas</h1>
<p>todos los usuarios con al menos una dirección y una factura</p>
<p><b>RAILS:</b>      Usuario.joins( direccions: :telefonos)</p>
<p><b>SQL:</b>        SELECT usuarios.* FROM usuarios
  INNER JOIN direccions ON usuarios.usuario_id= direccions.id
  INNER JOIN telefonos ON telefonos.direccion_id = direccions.id</p>
<table class ="table table-bordered">
  <thead>
    <tr>
      <th>id</th>
      <th>nombre</th>
      <th>apellido</th>
      <th>nacimiento</th>
      <th>sexo</th>
    </tr>
  </thead>

  <tbody>
    <% @ejemplo3.each do |usuario| %>
      <tr>
        <td><%= usuario.id %></td>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.nacimiento %></td>
        <td><%= usuario.sexo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>   

<h1>Ejemplo4: joins Unión entre tablas con condiciones</h1>
<p>todos los usuarios con al menos una dirección y una factura</p>
<p><b>RAILS:</b>      Usuario.joins(:direccions).where(direccions: {pais: 'Venezuela'})</p>
<p><b>SQL:</b>        SELECT usuarios.* FROM usuarios 
  INNER JOIN direccions ON direccions.usuario_id = usuarios.id 
  WHERE direccions.pais = 'Venezuela'</p>
<table class ="table table-bordered">
  <thead>
    <tr>
      <th>id</th>
      <th>nombre</th>
      <th>apellido</th>
      <th>nacimiento</th>
      <th>sexo</th>
    </tr>
  </thead>

  <tbody>
    <% @ejemplo4.each do |usuario| %>
      <tr>
        <td><%= usuario.id %></td>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.nacimiento %></td>
        <td><%= usuario.sexo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>   

<%= link_to 'Atrás', root_path %>

app/views/curso_activerecord/joins_sql.html.erb
<h1>Utilizando Segmentos SQL</h1>
<p>Todos los usuarios que tienen una al menos una direccion</p>
<p><b>RAILS:</b>      Usuario.joins('INNER JOIN direccions ON direccions.usuario_id = usuarios.id')</p>
<p><b>SQL:</b>        SELECT usuarios.* FROM usuarios INNER JOIN direccions ON direccions.usuario_id = usuarios.id</p>
<table class ="table table-bordered">
  <thead>
    <tr>
      <th>id</th>
      <th>nombre</th>
      <th>apellido</th>
      <th>nacimiento</th>
      <th>sexo</th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.id %></td>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.nacimiento %></td>
        <td><%= usuario.sexo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>   

<%= link_to 'Atrás', root_path %>

app/views/curso_activerecord/scope.html.erb
<h1>Ejemplo1: scope básico</h1>
<p>Todos los usuarios que tienen una al menos una direccion</p>
<p><b>RAILS:</b>      Usuario.masculino</p>
<p><b>SQL:</b>        SELECT usuarios.* FROM usuarios WHERE sexo = 'm'</p>
<table class ="table table-bordered">
  <thead>
    <tr>
      <th>id</th>
      <th>nombre</th>
      <th>apellido</th>
      <th>nacimiento</th>
      <th>sexo</th>
    </tr>
  </thead>

  <tbody>
    <% @ejemplo1.each do |usuario| %>
      <tr>
        <td><%= usuario.id %></td>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.nacimiento %></td>
        <td><%= usuario.sexo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>   


<h1>Ejemplo2: scope con argumentos</h1>
<p>todos los usuarios con al menos una dirección y una factura</p>
<p><b>RAILS:</b>      Usuario.mayor_que(Time.zone.parse("1988-05-09"))</p>
<p><b>SQL:</b>        SELECT usuarios.* FROM usuarios WHERE nacimiento < "1988-05-09"</p>
<table class ="table table-bordered">
  <thead>
    <tr>
      <th>id</th>
      <th>nombre</th>
      <th>apellido</th>
      <th>nacimiento</th>
      <th>sexo</th>
    </tr>
  </thead>

  <tbody>
    <% @ejemplo2.each do |usuario| %>
      <tr>
        <td><%= usuario.id %></td>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.nacimiento %></td>
        <td><%= usuario.sexo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>  

<h1>Ejemplo3: scope compuestos</h1>
<p>todos los usuarios con al menos una dirección y una factura</p>
<p><b>RAILS:</b>     Usuario.masculino.mayor_que(Time.zone.parse("1988-05-09"))</p>
<p><b>SQL:</b>       SELECT usuarios.* FROM usuarios WHERE nacimiento < "1988-05-09" and sexo ='m'</p>
<table class ="table table-bordered">
  <thead>
    <tr>
      <th>id</th>
      <th>nombre</th>
      <th>apellido</th>
      <th>nacimiento</th>
      <th>sexo</th>
    </tr>
  </thead>

  <tbody>
    <% @ejemplo3.each do |usuario| %>
      <tr>
        <td><%= usuario.id %></td>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.nacimiento %></td>
        <td><%= usuario.sexo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>   



<%= link_to 'Atrás', root_path %>

app/views/curso_validaciones/index.html.erb
<h1>Ejemplos del tutorial <a href="http://codehero.co/activerecord-validaciones/">Ruby on Rails desde cero: ActiveRecord Validaciones</a></h1>
<br> 
<%=  form_for :nuevo_usuario, url: validation_create_path  do |f| %>
  <% if @nuevo_usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nuevo_usuario.errors.count, "error") %> error antes de guardar:</h2>

      <ul>
      <% @nuevo_usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
    <div class="field">
    <%= f.label :email_confirmation %><br>
    <%= f.text_field :email_confirmation %>
  </div>
    <div class="field">
    <%= f.label :identificador %><br>
    <%= f.text_field :identificador %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br>
    <%= f.text_field :sexo %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<br>   

<h2>Datos de las tablas que estaremos utilizando</h2>
<h3>Usuarios</h3>

<table class ="table table-bordered">
  <thead>
    <tr>
      <th>identificador</th>
      <th>nombre</th>
      <th>email</th>
      <th>telefono</th>
      <th>sexo</th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.identificador %></td>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.telefono %></td>
        <td><%= usuario.sexo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>   

app/views/enviar_email/index.html.erb
<ul>
	<li><h3>Ruby on Rails desde Cero: Enviar emails (ActionMailer) </h3></li>
</ul>
<p>Para que funcione la emisión de correos se deben configurar el servidor de correos que estemos utilizando, este se ubica en la siguiente ruta</p>

<ul>
<li>config/environments/development.rb</li>
</ul>


		<pre>config.action_mailer.delivery_method = :smtp
		config.action_mailer.smtp_settings = {
		  address:              'smtp.gmail.com',
		  port:                 587,
		  domain:               'gmail.com',
		  user_name:            'codehero@gmail.com',
		  password:             'secret',
		  authentication:       'plain',
		  enable_starttls_auto: true  }</pre>

<p>En esta ruta se agregan los datos de su dirección de correo electrónico o servidor para q funcione</p>


<h3><a href="<%= email_send_path %>">Enviar correo electrónico </a></h3>

app/views/home/index.html.erb
<ul>
	<li><h3><a href="<%= join_path %>">Ruby on Rails desde Cero: ActiveRecord parte 2</a></h3></li>
	<li><h3><a href="<%= validation_path %>">Ruby on Rails desde cero: ActiveRecord Validaciones</a></h3></li>
	<li><h3><a href="<%= mensajes_path %>">Ruby on Rails desde cero: ActiveModel Validaciones y Serialización</a></h3></li>
	<li><h3><a href="<%= serializar_path %>">Ruby on Rails desde cero: Serializar Objetos (active_model_serializers) </a></h3></li>
	<li><h3><a href="<%= email_path %>"> Ruby on Rails desde Cero: Enviar emails (ActionMailer) </a></h3></li>



</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyOnRailsActiverecord</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" =>
  true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" =>
  true %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="http://www.gravatar.com/avatar/6352c71a03d5b247726deda291af1539?s=30"></head>
<body>
  <nav class="navbar-inverse navbar-fixed-top  " role="navigation">
    <div class='container'>
    <ul class="nav navbar-nav ">
      <li class="active">
        <a href="<%= root_path %>">Home</a>
      </li>
  <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          ActiveRecord parte 2 <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li>
            <a href="<%= join_path %>">inicio</a>
          </li>
          <li>
            <a href="<%= join_joinSQL_path %>">Joins con fragmentos de SQL</a>
          </li>
          <li>
            <a href="<%= join_join_path %>">Joins con herramientas Rails</a>
          </li>
          <li>
            <a href="<%= join_scope_path %>">Scope</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="<%= validation_path %>">ActiveRecord Validaciones</a>
      </li>
      <li>
        <a href="<%= mensajes_path %>">ActiveModel</a>
      </li>
            <li>
        <a href="<%= serializar_path %>">Serializar Objetos</a>
      </li>
  
    <li><a href="<%= email_path %>">ActionMailer </a></li>

</ul>

<ul class="nav navbar-nav pull-right" >


      <li>
        <a href="http://codehero.co/">CODEHERO</a>
      </li>

    </ul>


<!--     <ul class="nav navbar-nav navbar-right">
      <li ><a href="http://codehero.co/">CODEHERO</a></li>
    </ul> -->

</div>

  </nav>
  <div class="container main">

    <%= yield %></div>


    <footer>
      <div class="container">
      <h4><a href="http://codehero.co/">CodeHero.co</a></h4>

<p>Una iniciativa que nace de la falta de recursos educativos sobre tecnologías de información en español.</p>

</p>Funda en mayo de 2013 como un proyecto de cinco jóvenes venezolanos, residentes de la ciudad de Caracas, con el sueño de llevar los conocimientos adquiridos durante sus estudios y experiencias de trabajo, hasta las personas que no tienen acceso a ella, principalmente porque no entienden la lengua más hablada del internet, inglés.</p>
</div>
    </footer>

app/views/mensajes/index.html.erb
  <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: 'alert alert-success'%>

    <% end -%>

<div class ="col-sm-6">
<%= form_for @mensaje do |f| %>


  <% if @mensaje.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mensaje.errors.count, "error") %> antes de guardar:</h2>

      <ul>
      <% @mensaje.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <p> 
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :contenido, "Mensaje" %><br />
    <%= f.text_area :contenido %>
  </p>
  <p><%= f.submit "Enviar" %></p>
<% end %>

</div>
<div class ="col-sm-6">
<div class="list-group">
  <a href="<%= mensaje_json_path %>" class="list-group-item active">
    <h4 class="list-group-item-heading">Serialización Formato JSON</h4>
    <p class="list-group-item-text">Serializa un Objeto mensaje y lo imprime en formato JSON</p>
  </a>
    <a href="<%= mensaje_xml_path %>" class="list-group-item">
    <h4 class="list-group-item-heading">Serialización Formato XML</h4>
    <p class="list-group-item-text">Serializa un Objeto mensaje y lo imprime en formato XML</p>
  </a>
</div>
</div>

app/views/serializar_objeto/index.html.erb
<ul>
  <li><h3><a href="<%= serializar_basic_path %>">Serializar un objeto básico</a></h3></li>
  <li><h3><a href="<%= serializar_meta_path %>">Serializar un objeto agregandole metas</a></h3></li>
  <li><h3><a href="<%= serializar_custom_path %>">Serializar un Objeto con un serializador diferente al basico</a></h3></li>
</ul>